# Generated by Django 4.2.1 on 2023-05-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='femaleres',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='married',
            field=models.BooleanField(default=False),
        ),
    ]
