# Generated by Django 4.2.1 on 2023-05-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_feature_femaleres_alter_feature_married'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='ent_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='ent_nonagbusiness',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='ent_ownfarm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='ent_wagelabor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='fs_enoughtom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='fs_meat',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='fs_sleephun',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='labor_primary',
            field=models.BooleanField(default=False),
        ),
    ]
