# Generated by Django 4.2.1 on 2023-05-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_feature_ent_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='fs_meat',
            field=models.FloatField(),
        ),
    ]
