# Generated by Django 4.2.1 on 2023-05-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_feature_age_alter_feature_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='cons_social',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
