# Generated by Django 4.2.1 on 2023-05-17 13:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('therapists', '0003_appointmentbooked_delete_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentBooked',
            new_name='Appointment',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='therapist',
        ),
    ]
